package main;
/**
 * This class is generated by the inputReader after the program is launched.
 * The calculateHeight function is replaced by the function that given in the configurations within the menu
 */
public class HeightFunction{
	/**
	 * Calculates the height of the terrain at the given x and y position
	 * @param x the x position
	 * @param y the y position
	 * @return the height of the terrain at the given x and y position
	 */
	public static double calculateHeight(double x, double y){
		return 0;
	}
}